// flow-typed signature: e216ae3f3f637e84e82b435cdb3bdee1
// flow-typed version: <<STUB>>/slate-deep-table_v0.8.0/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-deep-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-deep-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-deep-table/all-debug' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/ALIGN' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/changes/insertColumn' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/changes/insertRow' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/changes/insertTable' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/changes/moveSelection' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/changes/moveSelectionBy' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/changes/removeColumn' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/changes/removeRow' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/changes/removeTable' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/changes/toggleHeaders' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/createAlign' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/createCell' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/createRow' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/createTable' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/defaultRenderers' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/makeSchema' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/onBackspace' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/onEnter' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/onTab' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/onUpDown' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/TablePosition' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/transforms/insertColumn' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/transforms/insertRow' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/transforms/insertTable' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/transforms/moveSelection' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/transforms/moveSelectionBy' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/transforms/removeColumn' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/transforms/removeRow' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/transforms/removeTable' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/transforms/setColumnAlign' {
  declare module.exports: any;
}

declare module 'slate-deep-table/dist/transforms/toggleHeaders' {
  declare module.exports: any;
}

declare module 'slate-deep-table/example/bundle' {
  declare module.exports: any;
}

declare module 'slate-deep-table/example/main' {
  declare module.exports: any;
}

declare module 'slate-deep-table/example/value' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/all' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/always-blocks-within-cells/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/always-blocks-within-cells/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/always-blocks-within-cells/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/basicTableInput' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/hyperscript' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-column-at/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-column-at/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-column-at/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-column/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-column/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-column/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-row/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-row/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-row/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-table/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-table/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/insert-table/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/move-table-selection-by/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/move-table-selection-by/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/move-table-selection-by/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/move-table-selection/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/move-table-selection/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/move-table-selection/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/query-isSelectionInTable/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/query-isSelectionInTable/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/query-isSelectionInTable/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-column-first/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-column-first/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-column-first/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-column-last-one/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-column-last-one/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-column-last-one/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-column/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-column/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-column/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-row-first/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-row-first/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-row-first/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-row-last-one/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-row-last-one/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-row-last-one/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-row/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-row/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-row/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-table/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-table/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/remove-table/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-no-blocks-within-rows/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-no-blocks-within-rows/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-no-blocks-within-rows/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-no-blocks-within-table/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-no-blocks-within-table/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-no-blocks-within-table/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-rows-cells-within-tables/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-rows-cells-within-tables/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-rows-cells-within-tables/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-rows-require-same-columns-counts/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-rows-require-same-columns-counts/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-rows-require-same-columns-counts/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-standard-table/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-standard-table/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-standard-table/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-tables-contain-rows/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-tables-contain-rows/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/schema-tables-contain-rows/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/serialize' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-insert-column/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-insert-column/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-insert-column/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-insert-row/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-insert-row/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-insert-row/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-insert-table/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-insert-table/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-insert-table/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-remove-column/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-remove-column/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-remove-column/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-remove-row/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-remove-row/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-remove-row/transform' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-remove-table/expected' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-remove-table/input' {
  declare module.exports: any;
}

declare module 'slate-deep-table/tests/undo-remove-table/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-deep-table/all-debug.js' {
  declare module.exports: $Exports<'slate-deep-table/all-debug'>;
}
declare module 'slate-deep-table/dist/ALIGN.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/ALIGN'>;
}
declare module 'slate-deep-table/dist/changes/insertColumn.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/changes/insertColumn'>;
}
declare module 'slate-deep-table/dist/changes/insertRow.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/changes/insertRow'>;
}
declare module 'slate-deep-table/dist/changes/insertTable.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/changes/insertTable'>;
}
declare module 'slate-deep-table/dist/changes/moveSelection.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/changes/moveSelection'>;
}
declare module 'slate-deep-table/dist/changes/moveSelectionBy.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/changes/moveSelectionBy'>;
}
declare module 'slate-deep-table/dist/changes/removeColumn.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/changes/removeColumn'>;
}
declare module 'slate-deep-table/dist/changes/removeRow.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/changes/removeRow'>;
}
declare module 'slate-deep-table/dist/changes/removeTable.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/changes/removeTable'>;
}
declare module 'slate-deep-table/dist/changes/toggleHeaders.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/changes/toggleHeaders'>;
}
declare module 'slate-deep-table/dist/createAlign.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/createAlign'>;
}
declare module 'slate-deep-table/dist/createCell.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/createCell'>;
}
declare module 'slate-deep-table/dist/createRow.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/createRow'>;
}
declare module 'slate-deep-table/dist/createTable.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/createTable'>;
}
declare module 'slate-deep-table/dist/defaultRenderers.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/defaultRenderers'>;
}
declare module 'slate-deep-table/dist/index' {
  declare module.exports: $Exports<'slate-deep-table/dist'>;
}
declare module 'slate-deep-table/dist/index.js' {
  declare module.exports: $Exports<'slate-deep-table/dist'>;
}
declare module 'slate-deep-table/dist/makeSchema.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/makeSchema'>;
}
declare module 'slate-deep-table/dist/onBackspace.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/onBackspace'>;
}
declare module 'slate-deep-table/dist/onEnter.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/onEnter'>;
}
declare module 'slate-deep-table/dist/onTab.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/onTab'>;
}
declare module 'slate-deep-table/dist/onUpDown.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/onUpDown'>;
}
declare module 'slate-deep-table/dist/TablePosition.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/TablePosition'>;
}
declare module 'slate-deep-table/dist/transforms/insertColumn.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/transforms/insertColumn'>;
}
declare module 'slate-deep-table/dist/transforms/insertRow.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/transforms/insertRow'>;
}
declare module 'slate-deep-table/dist/transforms/insertTable.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/transforms/insertTable'>;
}
declare module 'slate-deep-table/dist/transforms/moveSelection.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/transforms/moveSelection'>;
}
declare module 'slate-deep-table/dist/transforms/moveSelectionBy.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/transforms/moveSelectionBy'>;
}
declare module 'slate-deep-table/dist/transforms/removeColumn.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/transforms/removeColumn'>;
}
declare module 'slate-deep-table/dist/transforms/removeRow.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/transforms/removeRow'>;
}
declare module 'slate-deep-table/dist/transforms/removeTable.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/transforms/removeTable'>;
}
declare module 'slate-deep-table/dist/transforms/setColumnAlign.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/transforms/setColumnAlign'>;
}
declare module 'slate-deep-table/dist/transforms/toggleHeaders.js' {
  declare module.exports: $Exports<'slate-deep-table/dist/transforms/toggleHeaders'>;
}
declare module 'slate-deep-table/example/bundle.js' {
  declare module.exports: $Exports<'slate-deep-table/example/bundle'>;
}
declare module 'slate-deep-table/example/main.js' {
  declare module.exports: $Exports<'slate-deep-table/example/main'>;
}
declare module 'slate-deep-table/example/value.js' {
  declare module.exports: $Exports<'slate-deep-table/example/value'>;
}
declare module 'slate-deep-table/tests/all.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/all'>;
}
declare module 'slate-deep-table/tests/always-blocks-within-cells/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/always-blocks-within-cells/expected'>;
}
declare module 'slate-deep-table/tests/always-blocks-within-cells/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/always-blocks-within-cells/input'>;
}
declare module 'slate-deep-table/tests/always-blocks-within-cells/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/always-blocks-within-cells/transform'>;
}
declare module 'slate-deep-table/tests/basicTableInput.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/basicTableInput'>;
}
declare module 'slate-deep-table/tests/hyperscript.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/hyperscript'>;
}
declare module 'slate-deep-table/tests/insert-column-at/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-column-at/expected'>;
}
declare module 'slate-deep-table/tests/insert-column-at/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-column-at/input'>;
}
declare module 'slate-deep-table/tests/insert-column-at/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-column-at/transform'>;
}
declare module 'slate-deep-table/tests/insert-column/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-column/expected'>;
}
declare module 'slate-deep-table/tests/insert-column/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-column/input'>;
}
declare module 'slate-deep-table/tests/insert-column/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-column/transform'>;
}
declare module 'slate-deep-table/tests/insert-row/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-row/expected'>;
}
declare module 'slate-deep-table/tests/insert-row/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-row/input'>;
}
declare module 'slate-deep-table/tests/insert-row/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-row/transform'>;
}
declare module 'slate-deep-table/tests/insert-table/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-table/expected'>;
}
declare module 'slate-deep-table/tests/insert-table/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-table/input'>;
}
declare module 'slate-deep-table/tests/insert-table/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/insert-table/transform'>;
}
declare module 'slate-deep-table/tests/move-table-selection-by/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/move-table-selection-by/expected'>;
}
declare module 'slate-deep-table/tests/move-table-selection-by/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/move-table-selection-by/input'>;
}
declare module 'slate-deep-table/tests/move-table-selection-by/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/move-table-selection-by/transform'>;
}
declare module 'slate-deep-table/tests/move-table-selection/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/move-table-selection/expected'>;
}
declare module 'slate-deep-table/tests/move-table-selection/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/move-table-selection/input'>;
}
declare module 'slate-deep-table/tests/move-table-selection/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/move-table-selection/transform'>;
}
declare module 'slate-deep-table/tests/query-isSelectionInTable/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/query-isSelectionInTable/expected'>;
}
declare module 'slate-deep-table/tests/query-isSelectionInTable/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/query-isSelectionInTable/input'>;
}
declare module 'slate-deep-table/tests/query-isSelectionInTable/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/query-isSelectionInTable/transform'>;
}
declare module 'slate-deep-table/tests/remove-column-first/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-column-first/expected'>;
}
declare module 'slate-deep-table/tests/remove-column-first/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-column-first/input'>;
}
declare module 'slate-deep-table/tests/remove-column-first/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-column-first/transform'>;
}
declare module 'slate-deep-table/tests/remove-column-last-one/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-column-last-one/expected'>;
}
declare module 'slate-deep-table/tests/remove-column-last-one/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-column-last-one/input'>;
}
declare module 'slate-deep-table/tests/remove-column-last-one/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-column-last-one/transform'>;
}
declare module 'slate-deep-table/tests/remove-column/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-column/expected'>;
}
declare module 'slate-deep-table/tests/remove-column/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-column/input'>;
}
declare module 'slate-deep-table/tests/remove-column/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-column/transform'>;
}
declare module 'slate-deep-table/tests/remove-row-first/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-row-first/expected'>;
}
declare module 'slate-deep-table/tests/remove-row-first/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-row-first/input'>;
}
declare module 'slate-deep-table/tests/remove-row-first/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-row-first/transform'>;
}
declare module 'slate-deep-table/tests/remove-row-last-one/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-row-last-one/expected'>;
}
declare module 'slate-deep-table/tests/remove-row-last-one/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-row-last-one/input'>;
}
declare module 'slate-deep-table/tests/remove-row-last-one/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-row-last-one/transform'>;
}
declare module 'slate-deep-table/tests/remove-row/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-row/expected'>;
}
declare module 'slate-deep-table/tests/remove-row/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-row/input'>;
}
declare module 'slate-deep-table/tests/remove-row/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-row/transform'>;
}
declare module 'slate-deep-table/tests/remove-table/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-table/expected'>;
}
declare module 'slate-deep-table/tests/remove-table/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-table/input'>;
}
declare module 'slate-deep-table/tests/remove-table/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/remove-table/transform'>;
}
declare module 'slate-deep-table/tests/schema-no-blocks-within-rows/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-no-blocks-within-rows/expected'>;
}
declare module 'slate-deep-table/tests/schema-no-blocks-within-rows/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-no-blocks-within-rows/input'>;
}
declare module 'slate-deep-table/tests/schema-no-blocks-within-rows/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-no-blocks-within-rows/transform'>;
}
declare module 'slate-deep-table/tests/schema-no-blocks-within-table/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-no-blocks-within-table/expected'>;
}
declare module 'slate-deep-table/tests/schema-no-blocks-within-table/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-no-blocks-within-table/input'>;
}
declare module 'slate-deep-table/tests/schema-no-blocks-within-table/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-no-blocks-within-table/transform'>;
}
declare module 'slate-deep-table/tests/schema-rows-cells-within-tables/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-rows-cells-within-tables/expected'>;
}
declare module 'slate-deep-table/tests/schema-rows-cells-within-tables/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-rows-cells-within-tables/input'>;
}
declare module 'slate-deep-table/tests/schema-rows-cells-within-tables/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-rows-cells-within-tables/transform'>;
}
declare module 'slate-deep-table/tests/schema-rows-require-same-columns-counts/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-rows-require-same-columns-counts/expected'>;
}
declare module 'slate-deep-table/tests/schema-rows-require-same-columns-counts/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-rows-require-same-columns-counts/input'>;
}
declare module 'slate-deep-table/tests/schema-rows-require-same-columns-counts/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-rows-require-same-columns-counts/transform'>;
}
declare module 'slate-deep-table/tests/schema-standard-table/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-standard-table/expected'>;
}
declare module 'slate-deep-table/tests/schema-standard-table/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-standard-table/input'>;
}
declare module 'slate-deep-table/tests/schema-standard-table/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-standard-table/transform'>;
}
declare module 'slate-deep-table/tests/schema-tables-contain-rows/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-tables-contain-rows/expected'>;
}
declare module 'slate-deep-table/tests/schema-tables-contain-rows/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-tables-contain-rows/input'>;
}
declare module 'slate-deep-table/tests/schema-tables-contain-rows/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/schema-tables-contain-rows/transform'>;
}
declare module 'slate-deep-table/tests/serialize.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/serialize'>;
}
declare module 'slate-deep-table/tests/undo-insert-column/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-insert-column/expected'>;
}
declare module 'slate-deep-table/tests/undo-insert-column/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-insert-column/input'>;
}
declare module 'slate-deep-table/tests/undo-insert-column/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-insert-column/transform'>;
}
declare module 'slate-deep-table/tests/undo-insert-row/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-insert-row/expected'>;
}
declare module 'slate-deep-table/tests/undo-insert-row/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-insert-row/input'>;
}
declare module 'slate-deep-table/tests/undo-insert-row/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-insert-row/transform'>;
}
declare module 'slate-deep-table/tests/undo-insert-table/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-insert-table/expected'>;
}
declare module 'slate-deep-table/tests/undo-insert-table/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-insert-table/input'>;
}
declare module 'slate-deep-table/tests/undo-insert-table/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-insert-table/transform'>;
}
declare module 'slate-deep-table/tests/undo-remove-column/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-remove-column/expected'>;
}
declare module 'slate-deep-table/tests/undo-remove-column/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-remove-column/input'>;
}
declare module 'slate-deep-table/tests/undo-remove-column/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-remove-column/transform'>;
}
declare module 'slate-deep-table/tests/undo-remove-row/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-remove-row/expected'>;
}
declare module 'slate-deep-table/tests/undo-remove-row/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-remove-row/input'>;
}
declare module 'slate-deep-table/tests/undo-remove-row/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-remove-row/transform'>;
}
declare module 'slate-deep-table/tests/undo-remove-table/expected.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-remove-table/expected'>;
}
declare module 'slate-deep-table/tests/undo-remove-table/input.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-remove-table/input'>;
}
declare module 'slate-deep-table/tests/undo-remove-table/transform.js' {
  declare module.exports: $Exports<'slate-deep-table/tests/undo-remove-table/transform'>;
}
