// flow-typed signature: c7c0c33d727d48f6d94c83f938953f63
// flow-typed version: <<STUB>>/typeface-roboto_v0.0.75/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
