// flow-typed signature: 38b3397d1ee28c4b4b5fd4fd6ce3c29b
// flow-typed version: <<STUB>>/typeface-lato_v0.0.75/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-lato'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-lato' {
  declare module.exports: any;
}
