// flow-typed signature: ffb974b3e77927dca73721f1bddaba5f
// flow-typed version: <<STUB>>/typeface-montserrat_v0.0.75/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-montserrat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-montserrat' {
  declare module.exports: any;
}
