// flow-typed signature: 2c65624fba01e6d85adb7bbf6f4ca41d
// flow-typed version: <<STUB>>/typeface-roboto-mono_v0.0.75/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto-mono'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto-mono' {
  declare module.exports: any;
}
