// flow-typed signature: 947b158e0d6f7fc469c5efc32498f1cb
// flow-typed version: <<STUB>>/typeface-merriweather_v0.0.72/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-merriweather'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-merriweather' {
  declare module.exports: any;
}
