// flow-typed signature: c0118d0676914092e0d124d4a4db44c8
// flow-typed version: <<STUB>>/typeface-roboto-condensed_v0.0.75/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto-condensed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto-condensed' {
  declare module.exports: any;
}
