// flow-typed signature: e351f684e4ee6c4f739c8ef6c1c260a3
// flow-typed version: <<STUB>>/typeface-roboto-slab_v0.0.72/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto-slab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto-slab' {
  declare module.exports: any;
}
