// flow-typed signature: 195deb4a718d52ecc8427576f552728d
// flow-typed version: <<STUB>>/@convertkit/slate-lists_v0.2.4/flow_v0.108.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@convertkit/slate-lists'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@convertkit/slate-lists' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@convertkit/slate-lists/dist/index.esm' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/dist' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src/commands/decrease-list-item-depth' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src/commands/increase-list-item-depth' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src/commands/toggle-list' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src/commands/unwrap-list-by-key' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src/commands/unwrap-list' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src/commands/wrap-list' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src/create-commands' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src/create-normalize-node' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src/create-render-block' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src/create-schema' {
  declare module.exports: any;
}

declare module '@convertkit/slate-lists/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@convertkit/slate-lists/dist/index.esm.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/dist/index.esm'>;
}
declare module '@convertkit/slate-lists/dist/index' {
  declare module.exports: $Exports<'@convertkit/slate-lists/dist'>;
}
declare module '@convertkit/slate-lists/dist/index.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/dist'>;
}
declare module '@convertkit/slate-lists/src/commands/decrease-list-item-depth.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src/commands/decrease-list-item-depth'>;
}
declare module '@convertkit/slate-lists/src/commands/increase-list-item-depth.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src/commands/increase-list-item-depth'>;
}
declare module '@convertkit/slate-lists/src/commands/toggle-list.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src/commands/toggle-list'>;
}
declare module '@convertkit/slate-lists/src/commands/unwrap-list-by-key.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src/commands/unwrap-list-by-key'>;
}
declare module '@convertkit/slate-lists/src/commands/unwrap-list.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src/commands/unwrap-list'>;
}
declare module '@convertkit/slate-lists/src/commands/wrap-list.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src/commands/wrap-list'>;
}
declare module '@convertkit/slate-lists/src/create-commands.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src/create-commands'>;
}
declare module '@convertkit/slate-lists/src/create-normalize-node.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src/create-normalize-node'>;
}
declare module '@convertkit/slate-lists/src/create-render-block.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src/create-render-block'>;
}
declare module '@convertkit/slate-lists/src/create-schema.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src/create-schema'>;
}
declare module '@convertkit/slate-lists/src/index' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src'>;
}
declare module '@convertkit/slate-lists/src/index.js' {
  declare module.exports: $Exports<'@convertkit/slate-lists/src'>;
}
