version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
      # automerge all patch updates
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
      # allow minor updates to be merged for dev dependencies only
      - match:
          dependency_type: "development"
          update_type: "semver:minor"
