name: Styleguide Build
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy-styleguide:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install and build styleguide
        run: |
          yarn install
          yarn styleguide:build
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./styleguide
